### ISSUE TITLE
Could it work in Work Profile?

### ISSUE THREAD

**Issue by linsui** [oversecio/oversec#11]
I can't set oversec as accessibility service in Work Profile and I can't find app in Work Profile in oversec in Personal Profile.

**Comment by oversecio** [comment]
In might work, but has never be tested. 
You will probably have to install it manually again in the work profile.

**Comment by linsui** [comment]
oversec in personal profile can work with wechat in work profile though I can't find any app in work profile in the APPS tab. And oversec can only encrypt but decrypt. For another IM app TIM oversec can't work.

**Comment by oversecio** [comment]
From another user:

Your Oversec is great but it doesnt play well with Shelter (an app on f-droid that uses work profile to create duplicate app) as i couldn't deselect the app in my work profile as it is not on the app list in oversev setting page.
