### ISSUE TITLE
appname is shown as '__appname__' or '__APPNAME__'

### ISSUE THREAD

**Issue by linsui** [oversecio/oversec#26]

**Comment by oversecio** [comment]
Hi, not sure what you're referring to. Could you attach a screenshot please?

**Comment by linsui** [comment]
![screenshot_20190119-193043](https://user-images.githubusercontent.com/36977733/51426128-f1cd5980-1bdd-11e9-959a-4f59d42179bb.png)

**Comment by oversecio** [comment]
ah ok, sorry, fixing it

**Comment by oversecio** [comment]
thanks for reporting, I forgot to add the "zh-rCN" to my script.
Update should be out later this weekend!
