### ISSUE TITLE
Ask for setting again after update

### ISSUE THREAD

**Issue by linsui** [oversecio/oversec#44]
Oversec ask for Enabling as an Accessibility Service though it has been enabled. So I have to disable and enable it.

**Comment by oversecio** [comment]
Basically this shouldn't happen and I can't reproduce it so far.
Could you try to provide some more information / context like e.g.
* How frequent does this happen?  Daily?  Or more often?
* Can you think of any special action you have done on your phone that may have caused this? Maybe un-/installed  some other app. 
* Did you experience an Oversec *crash* / error message inbetween?

**Comment by linsui** [comment]
Sorry, I can provide nothing. It just happened after this update. If it happens again I will report.
