### ISSUE TITLE
fdroid releases above 1.5.5 were not found

### ISSUE THREAD

**Issue by danwdart** [oversecio/oversec#47]
Hello, on fdroid, 1.5.6 through 1.5.8 were 404ing. Please reupload or fix. thank you.

**Comment by oversecio** [comment]
Hi and sorry for the delay.

not sure I understand correctly.
Are you talking about the download links from here 

https://f-droid.org/en/packages/io.oversec.one/ 

If so, then probably this issue is obsolete as currently only versions 1.5.10,11,12 are shown and all of the links are working.

**Comment by danwdart** [comment]
I think this was fixed between our comments. It was that the latest three or so were 404ing at the time. Seems fixed now. Thanks
