### ISSUE TITLE
Notification problem

### ISSUE THREAD

**Issue by linsui** [oversecio/oversec#50]
Android 9.
When I use an app enabled Oversec and pull down, a notification from system that "Overlay is displaying over other app..." will show and disappear instantly, and the notification page will go back at the same time. But if there are some other notifications, the notification page won't go back. So could you prevent the system notification or just show a notification? Then the notification page won't go back.

**Comment by oversecio** [comment]
sorry, I can't reproduce this on an Emulator with Android 9 - I don't get any ""Overlay is displaying over other app..." in the first place.
What kind of phone / OS are you using exactly?
Or maybe there is a misunderstanding, can you send a screenshot?

**Comment by linsui** [comment]
I use PixelExperience ROM on Mi 6. The notification only shows when I pull down the notification page. And it will disappear instantly. I try to take a screenshot before it disappears.

![screenshot png](https://user-images.githubusercontent.com/36977733/53676754-c0e14980-3c9e-11e9-91cc-ba09b8e53de7.jpg)

**Comment by oversecio** [comment]
ok thanks. 
Coincidentially I'm planing to put PixelExperience on one of my phones this week anyway, so I'll see if I can reproduce it there..

**Comment by oversecio** [comment]
Hi, I'm running the latest PixelExperience ROM on a Xiamoi Poco F1, but I'm still not getting that notification.

I also checked, according to this:
https://www.androidpolice.com/2017/07/24/android-o-feature-spotlight-notifications-apps-displaying-apps-can-disabled/
if this is already disabled in my settings, but on Pie / PixelExperience there doesn't seem to be such settings - although you may want to double check on your phone.

**Comment by linsui** [comment]
I can't find this setting ,too, but I can disable other notifications now, great! :joy:
I have done more test:
1. VLC can displaying over other app but no notification.
2. I install oversec on Phh's AOSP 9 and get the same notification.
