### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by linsui** [oversecio/oversec#9]

**Comment by oversecio** [comment]
There is no easy / straightforward way for translations yet - but I might add this if enough people want to contribute translations.
Which language did you have in mind?

**Comment by linsui** [comment]
I use Simplified Chinese.

**Comment by oversecio** [comment]
Sounds good!

You can have a look at those two files first

[strings.xml](https://github.com/oversecio/oversec_crypto/blob/master/crypto/src/main/res/values/strings.xml)
[strings_core.xml](https://github.com/oversecio/oversec_crypto/blob/master/crypto/src/main/res/values/strings_core.xml)

to get an idea of the amount of text involved.

Easiest way to go forward would be to if you copy those files, edit them and send it back to me.

**Comment by linsui** [comment]
OK, I will pull request. 

https://github.com/oversecio/oversec_crypto/blob/2c5145b3fe2c5658870a8c9f1533d5bb827b3d55/crypto/src/main/res/values/strings_core.xml#L75

Maybe one more `.`

**Comment by MegaArthur** [comment]
I'd also be interested to translate (into Polish)

**Comment by oversecio** [comment]
Hi @MegaArthur - thanks that would be nice. Do you think you can work directly with GitHub and those XML files?

**Comment by MegaArthur** [comment]
I could try, but I have absolutely no experience with git. Can I just fetch the files, modify them and attach them here?

**Comment by oversecio** [comment]
Hi, sorry for the late reply.

> Can I just fetch the files, modify them and attach them here?

Yes, that would work !
